# Generated by Django 3.0.6 on 2020-10-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'отображение странцы в поиске',
                'verbose_name_plural': 'поиск по сайту',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/ins.png', upload_to='images/'),
        ),
    ]
