# Generated by Django 3.0.6 on 2020-10-29 22:09

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201026_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Телефон')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Тема звнока')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время получения сообщения')),
            ],
            options={
                'verbose_name': 'форма обратной связи',
                'verbose_name_plural': 'формы обратной связи',
            },
        ),
        migrations.CreateModel(
            name='SenderEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Тема сообщения')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Добавить рассылку',
                'verbose_name_plural': 'Создать рассылку',
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Выбрать изображение'),
        ),
        migrations.AlterField(
            model_name='images',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название изображения'),
        ),
        migrations.AlterField(
            model_name='pagelist',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст стрницы в поиске'),
        ),
        migrations.AlterField(
            model_name='pagelist',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='pagelist',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Основной текст новости'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата/время публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/No_image_available.svg.png', upload_to='images/', verbose_name='Загрузить картинку'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок новости'),
        ),
    ]
